language: java
jdk:
  - oraclejdk8

script:
  - cat ./src/test/resources/application.properties
  - mvn -P integration-test-azure clean verify
  - mvn -P integration-test-azure clean cobertura:cobertura-integration-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
